# Generated by Django 4.0.5 on 2022-07-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materia',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.IntegerField()),
                ('horas_au', models.IntegerField()),
                ('horas_cl', models.IntegerField()),
            ],
        ),
    ]
